"""
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

A = [1, 2]
sum = 2
i = 0
while True:
    k = A[-1] + A[-2]
    if k >= 4000000:
        break
    A.append(k)
    if i == 2:
        sum += k
        i = 0
    else:
        i += 1

print sum
